import { ChakraProvider, Flex } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider>
        <Flex direction="column" minH="100svh">
          <Navbar />
          {children}
        </Flex>
      </ChakraProvider>
    </>
  );
};

export default Layout;
